version: '3.8'
services:
  order-service:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/api/orders/revenue"]
      interval: 30s
      timeout: 10s
      retries: 3